# Variable substitution
# https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution
# 環境変数は local/Makefile で設定されています。
version: "3.7"
name: "govelte-todo_mw_localdev"
services:
  # https://www.envoyproxy.io/docs/envoy/latest/start/docker
  rproxy:
    image: envoyproxy/envoy:v1.30.1
    volumes:
      - ./envoy.yaml:/envoy.yaml
    ports:
      - 10000:10000
    command: -c /envoy.yaml
    networks:
      - network1

  apisvr:
    hostname: apisvr
    build:
      context: ../../backends/apisvr
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT_APISVR_GRPC}:${APP_PORT_APISVR_GRPC}"
    environment:
      - APP_CORS_ALLOW_ORIGINS=http://localhost:${APP_PORT_UISVR_HTTP},http://localhost:${APP_PORT_RPROXY_HTTP}
      - APP_FIREBASE_API_KEY=${APP_FIREBASE_API_KEY}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:${APP_FIREBASE_AUTH_PORT}
    networks:
      - network1

  uisvr:
    hostname: uisvr
    build:
      context: ../../frontends/uisvr
      dockerfile: Dockerfile
    environment:
      - PORT=${APP_PORT_UISVR_HTTP}
      - APP_FIREBASE_API_KEY=${APP_FIREBASE_API_KEY}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    volumes:
      - ./mounts/frontends/uisvr/.env:/srv/uisvr/.env
    ports:
      - "${APP_PORT_UISVR_HTTP}:${APP_PORT_UISVR_HTTP}"
    networks:
      - network1

  firebase-emulators:
    hostname: firebase-emulators
    build:
      context: ../../middlewares/firebase-emulators/local
      dockerfile: Dockerfile
    ports:
      - "${APP_FIREBASE_AUTH_PORT}:9099"
      - "${APP_FIREBASE_EMULATOR_SUITE_PORT}:4000"
    networks:
      - network1
    volumes:
      - ./data/firebase-emulators:/srv/firebase-emulators/data
    command: firebase emulators:start --import /srv/firebase-emulators/data/firebase --export-on-exit /srv/firebase-emulators/data/firebase

networks:
  network1:
