# Variable substitution
# https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution
# 環境変数は local/Makefile で設定されています。
name: "svelte-connect-todo-local"
services:
  firebase-emulators:
    hostname: firebase-emulators
    build:
      context: ../../middlewares/firebase-emulators/local
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT_FIREBASE_AUTH_dev}:9099"
      - "${APP_PORT_FIREBASE_EMULATOR_SUITE_dev}:4000"
    networks:
      - network1
    volumes:
      - ./data/firebase-emulators:/srv/firebase-emulators/data
    command: firebase emulators:start --import /srv/firebase-emulators/data/firebase --export-on-exit /srv/firebase-emulators/data/firebase

  mysql:
    image: mysql:8.0.38
    hostname: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${APP_MYSQL_DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "${APP_PORT_MYSQL_dev}:3306"
    volumes:
      - ../../middlewares/mysql/local/conf.d:/etc/mysql/conf.d
      - ./data/mysql/log/:/var/log/mysql
      - ./data/mysql/data:/var/lib/mysql
    networks:
      - network1

  apisvr:
    hostname: apisvr
    build:
      context: ../../backends/apisvr
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT_APISVR_dev}:${APP_PORT_APISVR_dev}"
    environment:
      - APP_CORS_ALLOW_ORIGINS=http://localhost:${APP_PORT_UISVR_dev},http://localhost:${APP_PORT_UISVR_e2e_test},http://localhost:${APP_PORT_RPROXY_dev}
      - APP_FIREBASE_API_KEY=${APP_FIREBASE_API_KEY}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:${APP_PORT_FIREBASE_AUTH_dev}
    networks:
      - network1

  uisvr:
    hostname: uisvr
    build:
      context: ../../frontends/uisvr
      dockerfile: Dockerfile
    environment:
      - PORT=${APP_PORT_UISVR_e2e_test}
      - APP_FIREBASE_API_KEY=${APP_FIREBASE_API_KEY}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    volumes:
      - ${APP_UISVR_DOT_ENV}:/srv/uisvr/.env
    ports:
      - "${APP_PORT_UISVR_e2e_test}:${APP_PORT_UISVR_e2e_test}"
    networks:
      - network1

  # https://www.envoyproxy.io/docs/envoy/latest/start/docker
  rproxy:
    image: envoyproxy/envoy:v1.30.1
    volumes:
      - ${APP_RPROXY_ENVOY_YAML}:/envoy.yaml
    ports:
      - ${APP_PORT_RPROXY_dev}:${APP_PORT_RPROXY_dev}
    command: -c /envoy.yaml
    networks:
      - network1

networks:
  network1:
